# fly.toml app configuration file generated for resumeapi on 2025-04-05T08:35:54+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "resumeapi"
primary_region = "fra"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/dotnet-core"]

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  ASPNETCORE_URLS = "http://+:8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
