name: .NET Tests

on:
  push:
    branches: [master]
    paths:
      - "api/**"
  pull_request:
    branches: [master]
    paths:
      - "api/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./api/ResumeApi.Tests

      # Build the test project
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./api/ResumeApi.Tests

      # Run tests with code coverage
      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
        working-directory: ./api/ResumeApi.Tests

      # Upload code coverage results
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-coverage-report
          path: ./api/ResumeApi.Tests/TestResults/
