name: React Tests

on:
  push:
    branches: [master]
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - "vitest.config.ts"
  pull_request:
    branches: [master]
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - "vitest.config.ts"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      # Install dependencies from package-lock.json
      - name: Install dependencies
        run: npm ci

      # Run tests with type checking disabled to avoid TS errors
      - name: Run tests
        run: npm run test:ci

      # Upload coverage reports as artifacts
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: react-coverage-report
          path: coverage/
